### ISSUE TITLE
インストール時、「DllRegisterServer への呼び出しはエラーコード 0x80008083 により失敗しました」エラーが出る

### ISSUE THREAD

**Issue by asakayu** [azumyar/voicepeak-connect#1]
# 内容: 
x64windows-install.batを「管理者として実行」した際にエラーが出て、おそらくインストールに失敗しています。

x64windows-install-x86.bat
x64windows-install-x64.bat
x64windows-install-as-x86.bat
どのbatを「管理者として実行」しても同じエラーでした。

# エラー内容: 
```
---------------------------
RegSvr32
---------------------------
モジュール "sapi-voicepeak-connect-x86.comhost.dll" は読み込まれましたが、DllRegisterServer への呼び出しはエラー コード 0x80008083 により失敗しました。

この問題の詳細については、エラー コードを検索語として入力してオンラインで検索してください。
---------------------------
OK   
---------------------------
```

## 再現性: 毎回

# 環境
sapi-voicepeak Version period.10 Mar 10, 2023 at 23:02
Windows10 pro 22H2
dotnet-sdk-6.0.411-win-x64インストール済
VoicePeakはC:\Program Files\VOICEPEAK\voicepeak.exeにインストールされています。

**Comment by azumyar** [comment]
zipを展開したディレクトリはどこでしょうか？私は未確認ですがCドライブ以外に展開すると正しく登録されないという情報があります。また末尾x86,x64はターゲットARCHなので使用するアプリに対応しているものをインストールしてください。(両方インストールしても問題は出ません)  
  
dllはバッチで登録した時点で登録されたディレクトリにあるものとされるため最終的に使用する場所に置いてからバッチを実行してください。

**Comment by asakayu** [comment]
回答くださりありがとうございます。

> zipを展開したディレクトリはどこでしょうか？私は未確認ですがCドライブ以外に展開すると正しく登録されないという情報があります。また末尾x86,x64はターゲットARCHなので使用するアプリに対応しているものをインストールしてください。(両方インストールしても問題は出ません)

末尾x86,x64のどちらも「DllRegisterServer への呼び出しはエラーコード 0x80008083 により失敗しました」エラーになります。
展開は元々Cドライブでしたが、Cドライブ直下で展開し直しても同じエラーが出ました。

> dllはバッチで登録した時点で登録されたディレクトリにあるものとされるため最終的に使用する場所に置いてからバッチを実行してください。

今回は[棒読みちゃん Ver0.1.11.0 β21](http://chi.usamimi.info/Program/Application/BouyomiChan/)での使用を考えております。この場合dllの「最終的に使用する場所」はどこになるでしょうか。
BouyomiChanフォルダにsapiフォルダを移動してx64windows-install-x86.batを実行、
あるいはBouyomiChanフォルダ直下にsapiフォルダ内のファイルをすべてコピーしてx64windows-install-x86.batを実行したところ、
エラーの表示が「モジュール "sapi-voicepeak-connect-x86.comhost.dll" の読み込みに失敗しました。」に変わりました。

```
---------------------------
RegSvr32
---------------------------
モジュール "sapi-voicepeak-connect-x86.comhost.dll" の読み込みに失敗しました。

バイナリが指定されたパスに格納されていることを確認するか、バイナリまたは依存 .DLL ファイルに問題がないかを調べてください。

指定されたモジュールが見つかりません。


---------------------------
OK   
---------------------------
```

**Comment by azumyar** [comment]
本題は調査中ですが取り急ぎ  
  
>今回は[棒読みちゃん Ver0.1.11.0 β21](http://chi.usamimi.info/Program/Application/BouyomiChan/)での使用を考えております。この場合dllの「最終的に使用する場所」はどこになるでしょうか。
  
最終的な場所は登録した場所で、インストールが動けばどこでもよいですが、インストールした場所からは動かさないでください。または再インストールしてください。  
  
>BouyomiChanフォルダにsapiフォルダを移動してx64windows-install-x86.batを実行、
あるいはBouyomiChanフォルダ直下にsapiフォルダ内のファイルをすべてコピーしてx64windows-install-x86.batを実行したところ、 
>エラーの表示が「モジュール "sapi-voicepeak-connect-x86.comhost.dll" の読み込みに失敗しました。」に変わりました。　　
  
棒読みちゃんは32bitなのでx64windows-install-x86.batで正しいですが、これは32bitなのでx86の.NET6ランタイムをインストールしてください。

**Comment by asakayu** [comment]
> 最終的な場所は登録した場所で、インストールが動けばどこでもよいですが、インストールした場所からは動かさないでく
ださい。または再インストールしてください。

アンインストールしてから再度インストール用の.batファイルを実行しても状況は変わりませんでした。
ちなみに、x64windows-uninstall-(x86 or x64).batを実行してもinstall時と同じ0x80008083エラーが出ます。

> 棒読みちゃんは32bitなのでx64windows-install-x86.batで正しいですが、これは32bitなのでx86の.NET6ランタイムをインストールしてください。

x64の.NET6ランタイムをインストールしておりました！棒読みちゃんに合わせたx86のランタイムが必要なのですね。
ただ、aspnetcore-runtime-6.0.19-win-x86をインストールしてみてもエラー状況は変わりありませんでした。

**Comment by azumyar** [comment]
いれているランタイムが違います。[デスクトップランタイム](https://dotnet.microsoft.com/ja-jp/download/dotnet/6.0)をいれてみてください。

**Comment by asakayu** [comment]
windowsdesktop-runtime-6.0.19-win-x86.exeをいれたところ、batのインストールの成功と棒読みちゃんでのvoicepeak東北きりたんの動作まで確認できました。
導入するランタイムを間違えていたせいでお騒がせしてしまい、大変申し訳ございませんでした。。

今のところつっかえることもなく棒読みちゃんに送った文章を読み上げられています。
便利なプラグインを作成くださり、改めて感謝申し上げます。
